### ISSUE TITLE
LBL seemingly ignoring the 'INPUT_FILE' parameter

### ISSUE THREAD

**Issue by asmasca** [njcuk9999/lbl#59]
Hi Neil

(Summary for other people that might read this) I found a problem today with the new version of LBL. It seems to be ignoring the "INPUT_FILE" parameter and trying to load the wrong types of files (CCF and BIS files), which leads to LBL crashing when the file size doesn't match the expectation. This was not happening in the old version I was using. I'm using the exact same data, within the exact same folder structure. 

[HARPS_03_lbl.zip](https://github.com/user-attachments/files/17950269/HARPS_03_lbl.zip)

Cheers
Alejandro

**Comment by njcuk9999** [comment]
Okay your wrap file looks good - I'll look into this as its odd its not working

**Comment by njcuk9999** [comment]
Okay this should be fixed in 0.64.013  - it was a problem with priority of the inputs, any input overridden by an instrument (`INPUT_FILE` is one of these set to `"*.fits"` in most cases) was taking precedence over user inputted variables - this shouldn't affect much else and will fix your problem!

Also I'm not sure why in your wrap file you are doing `from lbl.lbl import lbl_wrap`   it should be `from lbl import lbl_wrap` if you have installed lbl correctly.  (this looks like you are running the git files directly i.e. you are running the wrap file from above the github directory which you downloaded which is unwise)

**Comment by asmasca** [comment]
Hi Neil

Thanks for checking this. 

On the second question, the wrap files as created would only load from inside the dowloaded lbl directory (same place where the setup.py is). The installation process doesn't seem to have installed anything in any other place, and I cannot load it as a typical installed package. It created an empty folder in the home directory, and a "dist-info" directory with only a few text files (METADATA, entry points, etc.) inside the conda environment directory. 

Cheers
Alejandro

**Comment by njcuk9999** [comment]
Then something went very wrong. Could you send a copy of the command you are running to install and the printouts (starting from the conda create command)

**Comment by asmasca** [comment]
I reinstalled with the newest version. Now everything seems to be working fine, and it loads as a regular module.

**Comment by njcuk9999** [comment]
Okay good, I'll close this issue then!
